### ISSUE TITLE
P parameter cannot be set

### ISSUE THREAD

**Issue by mhk7** [sba1/mgsa-bioc#7]
Hi Sebastian,

I found a small bug in the MGSA package I think that I'm hoping will be easy for you to fix.  I've been using your package with great success (I love the idea and the package is very nice and easy to use), but unfortunately the package will not let me edit the parameter "p" away from the defaults.  I have managed to set my own custom grid for alpha and beta, but no matter what I set for p it just ignores this (including if I set it out of range - e.g. > 1 or < 0).  Any chance you could check on this?  I'm also poking around your GitHub repository to try to find the bug but haven't been able to yet.  I'm running R version 3.2.1, and I'm including an example of a command I've run to illustrate below.  Thanks for any help you can give!

Best,
Michael

PS. This bug is seen using mgsa version 1.16.0.  When I switch back to R 3.0.2 and use mgsa version 1.10.0 then I am able to set the p parameter (although now the multithreading part appears to be not working in this older version).

> s <- 1000000; fit_test = mgsa(x, myset, step=s, burnin=s/2, restarts=7,threads=0, p=c(10/length(myset), 20/length(myset), 30/length(myset), 40/length(myset), 50/length(myset),100/length(myset)),alpha=c(0.001, 0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1), beta=c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95, 0.97))

Warning message:
In mgsa(x, myset, step = s, burnin = s/2, restarts = 7, threads = 0,  :
  Specified observation contains 302 unmapple items. Excluded them from calculation.
> pPost(fit_test)
          value     estimate    std.error
1  2.805757e-05 0.000000e+00 0.000000e+00
2  8.729023e-05 0.000000e+00 0.000000e+00
3  1.465229e-04 0.000000e+00 0.000000e+00
4  2.057555e-04 0.000000e+00 0.000000e+00
5  2.649882e-04 0.000000e+00 0.000000e+00
6  3.242209e-04 0.000000e+00 0.000000e+00
7  3.834535e-04 2.857143e-05 2.857143e-05
8  4.426862e-04 1.114286e-03 5.500773e-04
9  5.019188e-04 4.365714e-02 8.338975e-03
10 5.611515e-04 9.552000e-01 8.843723e-03
> pPost(fit_test)[,1]*length(myset)
 [1]  1.000000  3.111111  5.222222  7.333333  9.444444 11.555556 13.666667 15.777778 17.888889 20.000000
> alphaPost(fit_test)
  value estimate std.error
1 0.001        0         0
2 0.005        0         0
3 0.010        1         0
4 0.020        0         0
5 0.030        0         0
6 0.040        0         0
7 0.050        0         0
8 0.100        0         0
> betaPost(fit_test)
   value  estimate std.error
1   0.10 0.0000000 0.0000000
2   0.20 0.0000000 0.0000000
3   0.30 0.0000000 0.0000000
4   0.40 0.0000000 0.0000000
5   0.50 0.0000000 0.0000000
6   0.60 0.0000000 0.0000000
7   0.70 0.0000000 0.0000000
8   0.80 0.0000000 0.0000000
9   0.85 0.0000000 0.0000000
10  0.90 0.0000000 0.0000000
11  0.91 0.1428571 0.1428571
12  0.92 0.2860000 0.1843541
13  0.93 0.5711429 0.2019296
14  0.94 0.0000000 0.0000000
15  0.95 0.0000000 0.0000000
16  0.97 0.0000000 0.0000000

**Comment by sba1** [comment]
I assume that it is fixed

**Comment by gokceneraslan** [comment]
mgsa function with "character, MgsaSets" signature is still broken:

```
> nrow(mgsa(c("A", "B"), new("MgsaSets", sets=list(set1 = LETTERS[1:3], set2 = LETTERS[2:4])), p=0.4)@pPost)
[1] 10
> nrow(mgsa(c("A", "B"), list(set1 = LETTERS[1:3], set2 = LETTERS[2:4]), p=0.4)@pPost)
[1] 1
```
